#!/bin/bash

#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_1.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_2.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_3.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_4.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_5.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_6.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_7.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_8.json'"
#
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_1.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_2.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_3.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_4.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_5.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_6.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_7.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_8.json'"
#
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_1.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_2.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_3.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_4.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_5.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_6.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_7.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_8.json'"

./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_9.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_10.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_11.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_12.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_13.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_14.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_15.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_16.json'"

./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_9.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_10.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_11.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_12.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_13.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_14.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_15.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_16.json'"

./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_1.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_2.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_3.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_4.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_5.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_6.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_7.json'"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_8.json'"
