#!/bin/bash

#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_1.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_2.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_3.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_4.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_5.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_6.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_7.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_8.json'"
#
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_9.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_10.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_11.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_12.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_13.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_14.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_15.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=2 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a2_16.json'"
#
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_1.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_2.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_3.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_4.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_5.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_6.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_7.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_8.json'"
#
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_9.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_10.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_11.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_12.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_13.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_14.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_15.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=3 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a3_16.json'"
#
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_1.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_2.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_3.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_4.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_5.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_6.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_7.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_8.json'"

#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_9.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_10.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_11.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_12.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_13.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_14.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_15.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=4 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a4_16.json'"
#
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_1.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_2.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_3.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_4.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_5.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_6.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_7.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=0 --m_alt=5 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_a5_8.json'"

#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=2 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d2_1.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=2 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d2_2.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=2 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d2_3.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=2 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d2_4.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=2 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d2_5.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=2 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d2_6.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=2 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d2_7.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=2 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d2_8.json'"
#
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=3 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d3_1.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=3 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d3_2.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=3 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d3_3.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=3 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d3_4.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=3 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d3_5.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=3 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d3_6.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=3 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d3_7.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=3 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d3_8.json'"
#
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=4 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d4_1.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=4 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d4_2.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=4 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d4_3.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=4 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d4_4.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=4 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d4_5.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=4 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d4_6.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=4 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d4_7.json'"
#./waf --pyrun "scratch/svcsim.py --timefail=20000 --m_dep=4 --m_alt=0 --fjson='simdata/mashupsall_dictapis.json' --filename='simdata/pwsvcsim_d4_8.json'"

./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_1.json' --filename='simdata/pwsvc_1.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_2.json' --filename='simdata/pwsvc_2.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_3.json' --filename='simdata/pwsvc_3.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_4.json' --filename='simdata/pwsvc_4.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_5.json' --filename='simdata/pwsvc_5.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_6.json' --filename='simdata/pwsvc_6.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_7.json' --filename='simdata/pwsvc_7.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_8.json' --filename='simdata/pwsvc_8.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_9.json' --filename='simdata/pwsvc_9.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_10.json' --filename='simdata/pwsvc_10.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_11.json' --filename='simdata/pwsvc_11.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_12.json' --filename='simdata/pwsvc_12.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_13.json' --filename='simdata/pwsvc_13.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_14.json' --filename='simdata/pwsvc_14.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_15.json' --filename='simdata/pwsvc_15.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_16.json' --filename='simdata/pwsvc_16.json' --fmt=1 --model=rand"
./waf --pyrun "scratch/svcsim.py --timefail=20000 --fjson='simdata/pwsvcsim_17.json' --filename='simdata/pwsvc_17.json' --fmt=1 --model=rand"
